# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{backup_data}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kris Leech"]
  s.date = %q{2010-08-27}
  s.description = %q{Backup and Compress Files and Database (mysql only) and send to user as a file (Rails Engine)}
  s.email = %q{kris.leech@interkonect.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/backups_controller.rb",
     "app/views/admin/backups/files.html.erb",
     "app/views/admin/backups/index.html.erb",
     "init.rb",
     "install.rb",
     "lib/backup_data.rb",
     "rails/init.rb",
     "test/backup_database_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/krisleech/backup_data}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Backup Files and Database Rails Engine}
  s.test_files = [
    "test/backup_database_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
